language: ruby
rvm:
  - 2.3.1
before_install:
  - nvm install node
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn
install:
  - yarn run brunch build
  - bundle install
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
