language: ruby
rvm:
  - 2.3.1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9
before_install:
  - nvm install
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev g++-4.9
  - yarn
env:
  - CXX=g++-4.9
install:
  - yarn run brunch build
  - bundle install
script:
  - rspec
  - yarn lint
  - yarn coverage
  - yarn report-coverage
cache:
  bundler: true
deploy:
  provider: script
  skip_cleanup: true
  script:
    - echo $DEPLOY_KEY > /tmp/deploy_key.enc
    - base64 --decode /tmp/deploy_key.enc > /tmp/deploy_key
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_key
    - ssh-add /tmp/deploy_key
    - git remote add dokku dokku@smallbutton.com:treasures
    - git push -f dokku master
  on:
    branch: production
addons:
  ssh_known_hosts: treasures.io
