codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range: 100..100
  round: down
  status:
    project:
      default:
        target: 100
    patch:
      default:
        target: 100
    changes:
      default:
        target: 100
parsers:
  v1:
    include_full_missed_files: true  # default false
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
